sudo: false
language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
notifications:
  email: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
compiler:
  - g++
